### ISSUE TITLE
Membership Cancellation Letter

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#163]
Hi Stella

We have come up with a cancellation letter that we would be interested in automating.
Here is a copy, we can talk about it the next meeting.

Thanks

[Cancellation Letter (Jim).docx](https://github.com/omnitekinc/AERA_MSS_Clients/files/1029886/Cancellation.Letter.Jim.docx)

**Comment by omnitekinc** [comment]
@sagarjagdish  Hi Sagar,
AERA would like to generate this letter for the member who's account have been expired more than 60days, there are 2 dynamic fields in the word doc, please take a look. This will be inside Export and should be called "Cancelation Letters", where Karen will select expiration dates for the members and generate PDFs.

**Comment by kbt1** [comment]
Works good. A few things to address: 
1- You need to adjust top Margin to fit into a #10 Window Envelope folded.
2- Also, the monthly payment is wrong amount for this one i pulled.
3- please be sure all current monthly payments are figured in.
4- This cancellation letter is for expired Membership only and not to include Prosis Accounts.
5- **Add Jims signature, I will have Steve post it here.**



[Cancelationletter - sample.pdf](https://github.com/omnitekinc/AERA_MSS_Clients/files/1042009/Cancelationletter.-.sample.pdf)

**Comment by stevefox3781** [comment]
![jim signatur](https://cloud.githubusercontent.com/assets/26387391/26699912/1d250c28-46e1-11e7-9c9a-347261c8965b.jpg)

**Comment by sagarjagdish** [comment]
1- You need to adjust top Margin to fit into a #10 Window Envelope folded.
=> Done and uploaded.

2- Also, the monthly payment is wrong amount for this one i pulled.
=> Now it's coming from the System Setting >> Pricing Screen. Please check and confirm.

3- please be sure all current monthly payments are figured in.
=> as per above comment now amount coming from the System Setting >> Pricing Screen. Please check and let us know if any change required in format.

4- This cancellation letter is for expired Membership only and not to include Prosis Accounts.
=> It's not exported for Prosis Account.

5- Add Jims signature, I will have Steve post it here.
=> added a signature as suggested.

Please verify all above change and let us know if any issue.

**Comment by kbt1** [comment]
#1. Top Margin = **2.5"**

On the customer address portion, please format like this:
**Contact Name
Company Name
Address
City, State Zip Code**

everything else looks good.

**Comment by sagarjagdish** [comment]
We have done with this change and uploaded on production. Please verify and confirm.

**Comment by kbt1** [comment]
please adjust top margin to 2"
it still isnt fitting right in the window envelope when folded.

**Comment by sagarjagdish** [comment]
It's already done on stage and production.

**Comment by kbt1** [comment]
prints perfect.
thank you!
